package com.androsa.doiamornament;

import com.androsa.doiamornament.block.*;
import com.androsa.doiamornament.data.BlockTagGenerator;
import com.androsa.doiamornament.data.ItemTagGenerator;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import com.google.common.collect.Lists;
import twilightforest.init.TFBlocks;

public class ModBlocks {

	public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, DoIAmOrnamentMod.MODID);
	public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, DoIAmOrnamentMod.MODID);
	public static final TFRegistryHelper HELPER = new TFRegistryHelper(BLOCKS, ITEMS);

	public static final RegistryObject<OrnamentTFStairs> ironwood_stairs = HELPER.stairs(TFBlocks.IRONWOOD_BLOCK, TFOrnamentBuilders.IRONWOOD, HELPER.array(BlockTagGenerator.BEACON_BASES), Lists.newArrayList());
	public static final RegistryObject<OrnamentTFStairs> fiery_stairs = HELPER.stairs(TFBlocks.FIERY_BLOCK, TFOrnamentBuilders.FIERY, HELPER.array(BlockTagGenerator.BEACON_BASES), Lists.newArrayList());
	public static final RegistryObject<OrnamentTFStairs> steeleaf_stairs = HELPER.stairs(TFBlocks.STEELEAF_BLOCK, TFOrnamentBuilders.STEELEAF, HELPER.array(BlockTagGenerator.BEACON_BASES), Lists.newArrayList());
	public static final RegistryObject<OrnamentTFStairs> arctic_fur_stairs = HELPER.stairs(TFBlocks.ARCTIC_FUR_BLOCK, TFOrnamentBuilders.ARCTIC_FUR, HELPER.array(BlockTagGenerator.BEACON_BASES), Lists.newArrayList());
	public static final RegistryObject<OrnamentTFStairs> carminite_stairs = HELPER.stairs(TFBlocks.CARMINITE_BLOCK, TFOrnamentBuilders.CARMINITE, HELPER.array(BlockTagGenerator.BEACON_BASES), Lists.newArrayList());
	public static final RegistryObject<OrnamentTFStairs> twilight_oak_log_stairs = HELPER.stairs(TFBlocks.TWILIGHT_OAK_LOG, TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final RegistryObject<OrnamentTFStairs> canopy_log_stairs = HELPER.stairs(TFBlocks.CANOPY_LOG, TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final RegistryObject<OrnamentTFStairs> mangrove_log_stairs = HELPER.stairs(TFBlocks.MANGROVE_LOG, TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final RegistryObject<OrnamentTFStairs> dark_oak_log_stairs = HELPER.stairs(TFBlocks.DARK_LOG, TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final RegistryObject<OrnamentTFStairs> time_log_stairs = HELPER.stairs(TFBlocks.TIME_LOG, TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final RegistryObject<OrnamentTFStairs> transformation_log_stairs = HELPER.stairs(TFBlocks.TRANSFORMATION_LOG, TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final RegistryObject<OrnamentTFStairs> mining_log_stairs = HELPER.stairs(TFBlocks.MINING_LOG, TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final RegistryObject<OrnamentTFStairs> sorting_log_stairs = HELPER.stairs(TFBlocks.SORTING_LOG, TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));

	public static final RegistryObject<OrnamentTFSlab> ironwood_slab = HELPER.slab(TFOrnamentBuilders.IRONWOOD);
	public static final RegistryObject<OrnamentTFSlab> fiery_slab = HELPER.slab(TFOrnamentBuilders.FIERY);
	public static final RegistryObject<OrnamentTFSlab> steeleaf_slab = HELPER.slab(TFOrnamentBuilders.STEELEAF);
	public static final RegistryObject<OrnamentTFSlab> arctic_fur_slab = HELPER.slab(TFOrnamentBuilders.ARCTIC_FUR);
	public static final RegistryObject<OrnamentTFSlab> carminite_slab = HELPER.slab(TFOrnamentBuilders.CARMINITE);
	public static final RegistryObject<OrnamentTFSlab> twilight_oak_log_slab = HELPER.slab(TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final RegistryObject<OrnamentTFSlab> canopy_log_slab = HELPER.slab(TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final RegistryObject<OrnamentTFSlab> mangrove_log_slab = HELPER.slab(TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final RegistryObject<OrnamentTFSlab> dark_oak_log_slab = HELPER.slab(TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final RegistryObject<OrnamentTFSlab> time_log_slab = HELPER.slab(TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final RegistryObject<OrnamentTFSlab> transformation_log_slab = HELPER.slab(TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final RegistryObject<OrnamentTFSlab> mining_log_slab = HELPER.slab(TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final RegistryObject<OrnamentTFSlab> sorting_log_slab = HELPER.slab(TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));

	public static final RegistryObject<OrnamentTFFence> ironwood_fence = HELPER.fence(TFOrnamentBuilders.IRONWOOD);
	public static final RegistryObject<OrnamentTFFence> fiery_fence = HELPER.fence(TFOrnamentBuilders.FIERY);
	public static final RegistryObject<OrnamentTFFence> steeleaf_fence = HELPER.fence(TFOrnamentBuilders.STEELEAF);
	public static final RegistryObject<OrnamentTFFence> arctic_fur_fence = HELPER.fence(TFOrnamentBuilders.ARCTIC_FUR);
	public static final RegistryObject<OrnamentTFFence> carminite_fence = HELPER.fence(TFOrnamentBuilders.CARMINITE);
	public static final RegistryObject<OrnamentTFFence> twilight_oak_log_fence = HELPER.fence(TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final RegistryObject<OrnamentTFFence> canopy_log_fence = HELPER.fence(TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final RegistryObject<OrnamentTFFence> mangrove_log_fence = HELPER.fence(TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final RegistryObject<OrnamentTFFence> dark_oak_log_fence = HELPER.fence(TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final RegistryObject<OrnamentTFFence> time_log_fence = HELPER.fence(TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final RegistryObject<OrnamentTFFence> transformation_log_fence = HELPER.fence(TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final RegistryObject<OrnamentTFFence> mining_log_fence = HELPER.fence(TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final RegistryObject<OrnamentTFFence> sorting_log_fence = HELPER.fence(TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));

	public static final RegistryObject<OrnamentTFTrapdoor> ironwood_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.IRONWOOD);
	public static final RegistryObject<OrnamentTFTrapdoor> fiery_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.FIERY);
	public static final RegistryObject<OrnamentTFTrapdoor> steeleaf_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.STEELEAF);
	public static final RegistryObject<OrnamentTFTrapdoor> arctic_fur_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.ARCTIC_FUR);
	public static final RegistryObject<OrnamentTFTrapdoor> carminite_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.CARMINITE);
	public static final RegistryObject<OrnamentTFTrapdoor> twilight_oak_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final RegistryObject<OrnamentTFTrapdoor> canopy_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final RegistryObject<OrnamentTFTrapdoor> mangrove_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final RegistryObject<OrnamentTFTrapdoor> dark_oak_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final RegistryObject<OrnamentTFTrapdoor> time_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final RegistryObject<OrnamentTFTrapdoor> transformation_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final RegistryObject<OrnamentTFTrapdoor> mining_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final RegistryObject<OrnamentTFTrapdoor> sorting_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));

	public static final RegistryObject<OrnamentTFFenceGate> ironwood_fence_gate = HELPER.fencegate(TFOrnamentBuilders.IRONWOOD);
	public static final RegistryObject<OrnamentTFFenceGate> fiery_fence_gate = HELPER.fencegate(TFOrnamentBuilders.FIERY);
	public static final RegistryObject<OrnamentTFFenceGate> steeleaf_fence_gate = HELPER.fencegate(TFOrnamentBuilders.STEELEAF);
	public static final RegistryObject<OrnamentTFFenceGate> arctic_fur_fence_gate = HELPER.fencegate(TFOrnamentBuilders.ARCTIC_FUR);
	public static final RegistryObject<OrnamentTFFenceGate> carminite_fence_gate = HELPER.fencegate(TFOrnamentBuilders.CARMINITE);
	public static final RegistryObject<OrnamentTFFenceGate> twilight_oak_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final RegistryObject<OrnamentTFFenceGate> canopy_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final RegistryObject<OrnamentTFFenceGate> mangrove_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final RegistryObject<OrnamentTFFenceGate> dark_oak_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final RegistryObject<OrnamentTFFenceGate> time_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final RegistryObject<OrnamentTFFenceGate> transformation_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final RegistryObject<OrnamentTFFenceGate> mining_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final RegistryObject<OrnamentTFFenceGate> sorting_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));

	public static final RegistryObject<OrnamentTFDoor> ironwood_door = HELPER.door(TFOrnamentBuilders.IRONWOOD);
	public static final RegistryObject<OrnamentTFDoor> fiery_door = HELPER.door(TFOrnamentBuilders.FIERY);
	public static final RegistryObject<OrnamentTFDoor> steeleaf_door = HELPER.door(TFOrnamentBuilders.STEELEAF);
	public static final RegistryObject<OrnamentTFDoor> arctic_fur_door = HELPER.door(TFOrnamentBuilders.ARCTIC_FUR);
	public static final RegistryObject<OrnamentTFDoor> carminite_door = HELPER.door(TFOrnamentBuilders.CARMINITE);
	public static final RegistryObject<OrnamentTFDoor> twilight_oak_log_door = HELPER.door(TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final RegistryObject<OrnamentTFDoor> canopy_log_door = HELPER.door(TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final RegistryObject<OrnamentTFDoor> mangrove_log_door = HELPER.door(TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final RegistryObject<OrnamentTFDoor> dark_oak_log_door = HELPER.door(TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final RegistryObject<OrnamentTFDoor> time_log_door = HELPER.door(TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final RegistryObject<OrnamentTFDoor> transformation_log_door = HELPER.door(TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final RegistryObject<OrnamentTFDoor> mining_log_door = HELPER.door(TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final RegistryObject<OrnamentTFDoor> sorting_log_door = HELPER.door(TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));

	public static final RegistryObject<OrnamentTFPole> ironwood_pole = HELPER.pole(TFOrnamentBuilders.IRONWOOD);
	public static final RegistryObject<OrnamentTFPole> fiery_pole = HELPER.pole(TFOrnamentBuilders.FIERY);
	public static final RegistryObject<OrnamentTFPole> steeleaf_pole = HELPER.pole(TFOrnamentBuilders.STEELEAF);
	public static final RegistryObject<OrnamentTFPole> arctic_fur_pole = HELPER.pole(TFOrnamentBuilders.ARCTIC_FUR);
	public static final RegistryObject<OrnamentTFPole> carminite_pole = HELPER.pole(TFOrnamentBuilders.CARMINITE);
	public static final RegistryObject<OrnamentTFPole> twilight_oak_log_pole = HELPER.pole(TFOrnamentBuilders.TWILIGHT_OAK_LOG);
	public static final RegistryObject<OrnamentTFPole> canopy_log_pole = HELPER.pole(TFOrnamentBuilders.CANOPY_LOG);
	public static final RegistryObject<OrnamentTFPole> mangrove_log_pole = HELPER.pole(TFOrnamentBuilders.MANGROVE_LOG);
	public static final RegistryObject<OrnamentTFPole> dark_oak_log_pole = HELPER.pole(TFOrnamentBuilders.DARK_OAK_LOG);
	public static final RegistryObject<OrnamentTFPole> time_log_pole = HELPER.pole(TFOrnamentBuilders.TIME_LOG);
	public static final RegistryObject<OrnamentTFPole> transformation_log_pole = HELPER.pole(TFOrnamentBuilders.TRANSFORMATION_LOG);
	public static final RegistryObject<OrnamentTFPole> mining_log_pole = HELPER.pole(TFOrnamentBuilders.MINING_LOG);
	public static final RegistryObject<OrnamentTFPole> sorting_log_pole = HELPER.pole(TFOrnamentBuilders.SORTING_LOG);
	public static final RegistryObject<OrnamentTFPole> twilight_oak_plank_pole = HELPER.pole(TFOrnamentBuilders.TWILIGHT_OAK_PLANKS);
	public static final RegistryObject<OrnamentTFPole> canopy_plank_pole = HELPER.pole(TFOrnamentBuilders.CANOPY_PLANKS);
	public static final RegistryObject<OrnamentTFPole> mangrove_plank_pole = HELPER.pole(TFOrnamentBuilders.MANGROVE_PLANKS);
	public static final RegistryObject<OrnamentTFPole> dark_oak_plank_pole = HELPER.pole(TFOrnamentBuilders.DARK_OAK_PLANKS);
	public static final RegistryObject<OrnamentTFPole> time_plank_pole = HELPER.pole(TFOrnamentBuilders.TIME_PLANKS);
	public static final RegistryObject<OrnamentTFPole> transformation_plank_pole = HELPER.pole(TFOrnamentBuilders.TRANSFORMATION_PLANKS);
	public static final RegistryObject<OrnamentTFPole> mining_plank_pole = HELPER.pole(TFOrnamentBuilders.MINING_PLANKS);
	public static final RegistryObject<OrnamentTFPole> sorting_plank_pole = HELPER.pole(TFOrnamentBuilders.SORTING_PLANKS);

	public static final RegistryObject<OrnamentTFBeam> ironwood_beam = HELPER.beam(TFOrnamentBuilders.IRONWOOD);
	public static final RegistryObject<OrnamentTFBeam> fiery_beam = HELPER.beam(TFOrnamentBuilders.FIERY);
	public static final RegistryObject<OrnamentTFBeam> steeleaf_beam = HELPER.beam(TFOrnamentBuilders.STEELEAF);
	public static final RegistryObject<OrnamentTFBeam> arctic_fur_beam = HELPER.beam(TFOrnamentBuilders.ARCTIC_FUR);
	public static final RegistryObject<OrnamentTFBeam> carminite_beam = HELPER.beam(TFOrnamentBuilders.CARMINITE);
	public static final RegistryObject<OrnamentTFBeam> twilight_oak_log_beam = HELPER.beam(TFOrnamentBuilders.TWILIGHT_OAK_LOG);
	public static final RegistryObject<OrnamentTFBeam> canopy_log_beam = HELPER.beam(TFOrnamentBuilders.CANOPY_LOG);
	public static final RegistryObject<OrnamentTFBeam> mangrove_log_beam = HELPER.beam(TFOrnamentBuilders.MANGROVE_LOG);
	public static final RegistryObject<OrnamentTFBeam> dark_oak_log_beam = HELPER.beam(TFOrnamentBuilders.DARK_OAK_LOG);
	public static final RegistryObject<OrnamentTFBeam> time_log_beam = HELPER.beam(TFOrnamentBuilders.TIME_LOG);
	public static final RegistryObject<OrnamentTFBeam> transformation_log_beam = HELPER.beam(TFOrnamentBuilders.TRANSFORMATION_LOG);
	public static final RegistryObject<OrnamentTFBeam> mining_log_beam = HELPER.beam(TFOrnamentBuilders.MINING_LOG);
	public static final RegistryObject<OrnamentTFBeam> sorting_log_beam = HELPER.beam(TFOrnamentBuilders.SORTING_LOG);
	public static final RegistryObject<OrnamentTFBeam> twilight_oak_plank_beam = HELPER.beam(TFOrnamentBuilders.TWILIGHT_OAK_PLANKS);
	public static final RegistryObject<OrnamentTFBeam> canopy_plank_beam = HELPER.beam(TFOrnamentBuilders.CANOPY_PLANKS);
	public static final RegistryObject<OrnamentTFBeam> mangrove_plank_beam = HELPER.beam(TFOrnamentBuilders.MANGROVE_PLANKS);
	public static final RegistryObject<OrnamentTFBeam> dark_oak_plank_beam = HELPER.beam(TFOrnamentBuilders.DARK_OAK_PLANKS);
	public static final RegistryObject<OrnamentTFBeam> time_plank_beam = HELPER.beam(TFOrnamentBuilders.TIME_PLANKS);
	public static final RegistryObject<OrnamentTFBeam> transformation_plank_beam = HELPER.beam(TFOrnamentBuilders.TRANSFORMATION_PLANKS);
	public static final RegistryObject<OrnamentTFBeam> mining_plank_beam = HELPER.beam(TFOrnamentBuilders.MINING_PLANKS);
	public static final RegistryObject<OrnamentTFBeam> sorting_plank_beam = HELPER.beam(TFOrnamentBuilders.SORTING_PLANKS);

	public static final RegistryObject<OrnamentTFWall> ironwood_wall = HELPER.wall(TFOrnamentBuilders.IRONWOOD);
	public static final RegistryObject<OrnamentTFWall> fiery_wall = HELPER.wall(TFOrnamentBuilders.FIERY);
	public static final RegistryObject<OrnamentTFWall> steeleaf_wall = HELPER.wall(TFOrnamentBuilders.STEELEAF);
	public static final RegistryObject<OrnamentTFWall> arctic_fur_wall = HELPER.wall(TFOrnamentBuilders.ARCTIC_FUR);
	public static final RegistryObject<OrnamentTFWall> carminite_wall = HELPER.wall(TFOrnamentBuilders.CARMINITE);
	public static final RegistryObject<OrnamentTFWall> twilight_oak_log_wall = HELPER.wall(TFOrnamentBuilders.TWILIGHT_OAK_LOG);
	public static final RegistryObject<OrnamentTFWall> canopy_log_wall = HELPER.wall(TFOrnamentBuilders.CANOPY_LOG);
	public static final RegistryObject<OrnamentTFWall> mangrove_log_wall = HELPER.wall(TFOrnamentBuilders.MANGROVE_LOG);
	public static final RegistryObject<OrnamentTFWall> dark_oak_log_wall = HELPER.wall(TFOrnamentBuilders.DARK_OAK_LOG);
	public static final RegistryObject<OrnamentTFWall> time_log_wall = HELPER.wall(TFOrnamentBuilders.TIME_LOG);
	public static final RegistryObject<OrnamentTFWall> transformation_log_wall = HELPER.wall(TFOrnamentBuilders.TRANSFORMATION_LOG);
	public static final RegistryObject<OrnamentTFWall> mining_log_wall = HELPER.wall(TFOrnamentBuilders.MINING_LOG);
	public static final RegistryObject<OrnamentTFWall> sorting_log_wall = HELPER.wall(TFOrnamentBuilders.SORTING_LOG);
	public static final RegistryObject<OrnamentTFWall> twilight_oak_plank_wall = HELPER.wall(TFOrnamentBuilders.TWILIGHT_OAK_PLANKS);
	public static final RegistryObject<OrnamentTFWall> canopy_plank_wall = HELPER.wall(TFOrnamentBuilders.CANOPY_PLANKS);
	public static final RegistryObject<OrnamentTFWall> mangrove_plank_wall = HELPER.wall(TFOrnamentBuilders.MANGROVE_PLANKS);
	public static final RegistryObject<OrnamentTFWall> dark_oak_plank_wall = HELPER.wall(TFOrnamentBuilders.DARK_OAK_PLANKS);
	public static final RegistryObject<OrnamentTFWall> time_plank_wall = HELPER.wall(TFOrnamentBuilders.TIME_PLANKS);
	public static final RegistryObject<OrnamentTFWall> transformation_plank_wall = HELPER.wall(TFOrnamentBuilders.TRANSFORMATION_PLANKS);
	public static final RegistryObject<OrnamentTFWall> mining_plank_wall = HELPER.wall(TFOrnamentBuilders.MINING_PLANKS);
	public static final RegistryObject<OrnamentTFWall> sorting_plank_wall = HELPER.wall(TFOrnamentBuilders.SORTING_PLANKS);

	public static final RegistryObject<OrnamentTFSaddleDoor> ironwood_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.IRONWOOD);
	public static final RegistryObject<OrnamentTFSaddleDoor> fiery_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.FIERY);
	public static final RegistryObject<OrnamentTFSaddleDoor> steeleaf_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.STEELEAF);
	public static final RegistryObject<OrnamentTFSaddleDoor> arctic_fur_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.ARCTIC_FUR);
	public static final RegistryObject<OrnamentTFSaddleDoor> carminite_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.CARMINITE);
	public static final RegistryObject<OrnamentTFSaddleDoor> twilight_oak_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TWILIGHT_OAK_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> canopy_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.CANOPY_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> mangrove_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MANGROVE_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> dark_oak_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.DARK_OAK_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> time_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TIME_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> transformation_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TRANSFORMATION_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> mining_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MINING_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> sorting_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.SORTING_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> twilight_oak_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TWILIGHT_OAK_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> canopy_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.CANOPY_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> mangrove_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MANGROVE_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> dark_oak_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.DARK_OAK_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> time_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TIME_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> transformation_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TRANSFORMATION_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> mining_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MINING_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> sorting_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.SORTING_PLANKS);
}
