package com.androsa.doiamornament;

import com.androsa.doiamornament.block.*;
import com.androsa.doiamornament.data.BlockTagGenerator;
import com.androsa.doiamornament.data.ItemTagGenerator;
import com.google.common.collect.Lists;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.function.Supplier;

public class ModBlocks {

	public static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(DoIAmOrnamentMod.MODID);
	public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(DoIAmOrnamentMod.MODID);
	public static final TFRegistryHelper HELPER = new TFRegistryHelper(BLOCKS, ITEMS);

	public static final Supplier<OrnamentTFStairs> ironwood_stairs = HELPER.stairs(TFOrnamentBuilders.IRONWOOD, HELPER.array(BlockTagGenerator.BEACON_BASES), Lists.newArrayList());
	public static final Supplier<OrnamentTFStairs> fiery_stairs = HELPER.stairs(TFOrnamentBuilders.FIERY, HELPER.array(BlockTagGenerator.BEACON_BASES), Lists.newArrayList());
	public static final Supplier<OrnamentTFStairs> steeleaf_stairs = HELPER.stairs(TFOrnamentBuilders.STEELEAF, HELPER.array(BlockTagGenerator.BEACON_BASES), Lists.newArrayList());
	public static final Supplier<OrnamentTFStairs> arctic_fur_stairs = HELPER.stairs(TFOrnamentBuilders.ARCTIC_FUR, HELPER.array(BlockTagGenerator.BEACON_BASES), Lists.newArrayList());
	public static final Supplier<OrnamentTFStairs> carminite_stairs = HELPER.stairs(TFOrnamentBuilders.CARMINITE, HELPER.array(BlockTagGenerator.BEACON_BASES), Lists.newArrayList());
	public static final Supplier<OrnamentTFStairs> twilight_oak_log_stairs = HELPER.stairs(TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final Supplier<OrnamentTFStairs> canopy_log_stairs = HELPER.stairs(TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final Supplier<OrnamentTFStairs> mangrove_log_stairs = HELPER.stairs(TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final Supplier<OrnamentTFStairs> dark_oak_log_stairs = HELPER.stairs(TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final Supplier<OrnamentTFStairs> time_log_stairs = HELPER.stairs(TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final Supplier<OrnamentTFStairs> transformation_log_stairs = HELPER.stairs(TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final Supplier<OrnamentTFStairs> mining_log_stairs = HELPER.stairs(TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));
	public static final Supplier<OrnamentTFStairs> sorting_log_stairs = HELPER.stairs(TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_STAIRS), HELPER.array(ItemTagGenerator.WOOD_STAIRS));

	public static final Supplier<OrnamentTFSlab> ironwood_slab = HELPER.slab(TFOrnamentBuilders.IRONWOOD);
	public static final Supplier<OrnamentTFSlab> fiery_slab = HELPER.slab(TFOrnamentBuilders.FIERY);
	public static final Supplier<OrnamentTFSlab> steeleaf_slab = HELPER.slab(TFOrnamentBuilders.STEELEAF);
	public static final Supplier<OrnamentTFSlab> arctic_fur_slab = HELPER.slab(TFOrnamentBuilders.ARCTIC_FUR);
	public static final Supplier<OrnamentTFSlab> carminite_slab = HELPER.slab(TFOrnamentBuilders.CARMINITE);
	public static final Supplier<OrnamentTFSlab> twilight_oak_log_slab = HELPER.slab(TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final Supplier<OrnamentTFSlab> canopy_log_slab = HELPER.slab(TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final Supplier<OrnamentTFSlab> mangrove_log_slab = HELPER.slab(TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final Supplier<OrnamentTFSlab> dark_oak_log_slab = HELPER.slab(TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final Supplier<OrnamentTFSlab> time_log_slab = HELPER.slab(TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final Supplier<OrnamentTFSlab> transformation_log_slab = HELPER.slab(TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final Supplier<OrnamentTFSlab> mining_log_slab = HELPER.slab(TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));
	public static final Supplier<OrnamentTFSlab> sorting_log_slab = HELPER.slab(TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_SLABS), HELPER.array(ItemTagGenerator.WOOD_SLABS));

	public static final Supplier<OrnamentTFFence> ironwood_fence = HELPER.fence(TFOrnamentBuilders.IRONWOOD);
	public static final Supplier<OrnamentTFFence> fiery_fence = HELPER.fence(TFOrnamentBuilders.FIERY);
	public static final Supplier<OrnamentTFFence> steeleaf_fence = HELPER.fence(TFOrnamentBuilders.STEELEAF);
	public static final Supplier<OrnamentTFFence> arctic_fur_fence = HELPER.fence(TFOrnamentBuilders.ARCTIC_FUR);
	public static final Supplier<OrnamentTFFence> carminite_fence = HELPER.fence(TFOrnamentBuilders.CARMINITE);
	public static final Supplier<OrnamentTFFence> twilight_oak_log_fence = HELPER.fence(TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final Supplier<OrnamentTFFence> canopy_log_fence = HELPER.fence(TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final Supplier<OrnamentTFFence> mangrove_log_fence = HELPER.fence(TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final Supplier<OrnamentTFFence> dark_oak_log_fence = HELPER.fence(TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final Supplier<OrnamentTFFence> time_log_fence = HELPER.fence(TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final Supplier<OrnamentTFFence> transformation_log_fence = HELPER.fence(TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final Supplier<OrnamentTFFence> mining_log_fence = HELPER.fence(TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));
	public static final Supplier<OrnamentTFFence> sorting_log_fence = HELPER.fence(TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCES), HELPER.array(ItemTagGenerator.WOOD_FENCES));

	public static final Supplier<OrnamentTFTrapdoor> ironwood_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.IRONWOOD);
	public static final Supplier<OrnamentTFTrapdoor> fiery_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.FIERY);
	public static final Supplier<OrnamentTFTrapdoor> steeleaf_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.STEELEAF);
	public static final Supplier<OrnamentTFTrapdoor> arctic_fur_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.ARCTIC_FUR);
	public static final Supplier<OrnamentTFTrapdoor> carminite_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.CARMINITE);
	public static final Supplier<OrnamentTFTrapdoor> twilight_oak_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final Supplier<OrnamentTFTrapdoor> canopy_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final Supplier<OrnamentTFTrapdoor> mangrove_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final Supplier<OrnamentTFTrapdoor> dark_oak_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final Supplier<OrnamentTFTrapdoor> time_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final Supplier<OrnamentTFTrapdoor> transformation_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final Supplier<OrnamentTFTrapdoor> mining_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));
	public static final Supplier<OrnamentTFTrapdoor> sorting_log_trapdoor = HELPER.trapdoor(TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_TRAPDOORS), HELPER.array(ItemTagGenerator.WOOD_TRAPDOORS));

	public static final Supplier<OrnamentTFFenceGate> ironwood_fence_gate = HELPER.fencegate(TFOrnamentBuilders.IRONWOOD);
	public static final Supplier<OrnamentTFFenceGate> fiery_fence_gate = HELPER.fencegate(TFOrnamentBuilders.FIERY);
	public static final Supplier<OrnamentTFFenceGate> steeleaf_fence_gate = HELPER.fencegate(TFOrnamentBuilders.STEELEAF);
	public static final Supplier<OrnamentTFFenceGate> arctic_fur_fence_gate = HELPER.fencegate(TFOrnamentBuilders.ARCTIC_FUR);
	public static final Supplier<OrnamentTFFenceGate> carminite_fence_gate = HELPER.fencegate(TFOrnamentBuilders.CARMINITE);
	public static final Supplier<OrnamentTFFenceGate> twilight_oak_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final Supplier<OrnamentTFFenceGate> canopy_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final Supplier<OrnamentTFFenceGate> mangrove_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final Supplier<OrnamentTFFenceGate> dark_oak_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final Supplier<OrnamentTFFenceGate> time_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final Supplier<OrnamentTFFenceGate> transformation_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final Supplier<OrnamentTFFenceGate> mining_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));
	public static final Supplier<OrnamentTFFenceGate> sorting_log_fence_gate = HELPER.fencegate(TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_FENCE_GATES), HELPER.array(ItemTagGenerator.WOOD_FENCE_GATES));

	public static final Supplier<OrnamentTFDoor> ironwood_door = HELPER.door(TFOrnamentBuilders.IRONWOOD);
	public static final Supplier<OrnamentTFDoor> fiery_door = HELPER.door(TFOrnamentBuilders.FIERY);
	public static final Supplier<OrnamentTFDoor> steeleaf_door = HELPER.door(TFOrnamentBuilders.STEELEAF);
	public static final Supplier<OrnamentTFDoor> arctic_fur_door = HELPER.door(TFOrnamentBuilders.ARCTIC_FUR);
	public static final Supplier<OrnamentTFDoor> carminite_door = HELPER.door(TFOrnamentBuilders.CARMINITE);
	public static final Supplier<OrnamentTFDoor> twilight_oak_log_door = HELPER.door(TFOrnamentBuilders.TWILIGHT_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final Supplier<OrnamentTFDoor> canopy_log_door = HELPER.door(TFOrnamentBuilders.CANOPY_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final Supplier<OrnamentTFDoor> mangrove_log_door = HELPER.door(TFOrnamentBuilders.MANGROVE_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final Supplier<OrnamentTFDoor> dark_oak_log_door = HELPER.door(TFOrnamentBuilders.DARK_OAK_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final Supplier<OrnamentTFDoor> time_log_door = HELPER.door(TFOrnamentBuilders.TIME_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final Supplier<OrnamentTFDoor> transformation_log_door = HELPER.door(TFOrnamentBuilders.TRANSFORMATION_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final Supplier<OrnamentTFDoor> mining_log_door = HELPER.door(TFOrnamentBuilders.MINING_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));
	public static final Supplier<OrnamentTFDoor> sorting_log_door = HELPER.door(TFOrnamentBuilders.SORTING_LOG, HELPER.array(BlockTagGenerator.WOOD_DOORS), HELPER.array(ItemTagGenerator.WOOD_DOORS));

	public static final Supplier<OrnamentTFPole> ironwood_pole = HELPER.pole(TFOrnamentBuilders.IRONWOOD);
	public static final Supplier<OrnamentTFPole> fiery_pole = HELPER.pole(TFOrnamentBuilders.FIERY);
	public static final Supplier<OrnamentTFPole> steeleaf_pole = HELPER.pole(TFOrnamentBuilders.STEELEAF);
	public static final Supplier<OrnamentTFPole> arctic_fur_pole = HELPER.pole(TFOrnamentBuilders.ARCTIC_FUR);
	public static final Supplier<OrnamentTFPole> carminite_pole = HELPER.pole(TFOrnamentBuilders.CARMINITE);
	public static final Supplier<OrnamentTFPole> twilight_oak_log_pole = HELPER.pole(TFOrnamentBuilders.TWILIGHT_OAK_LOG);
	public static final Supplier<OrnamentTFPole> canopy_log_pole = HELPER.pole(TFOrnamentBuilders.CANOPY_LOG);
	public static final Supplier<OrnamentTFPole> mangrove_log_pole = HELPER.pole(TFOrnamentBuilders.MANGROVE_LOG);
	public static final Supplier<OrnamentTFPole> dark_oak_log_pole = HELPER.pole(TFOrnamentBuilders.DARK_OAK_LOG);
	public static final Supplier<OrnamentTFPole> time_log_pole = HELPER.pole(TFOrnamentBuilders.TIME_LOG);
	public static final Supplier<OrnamentTFPole> transformation_log_pole = HELPER.pole(TFOrnamentBuilders.TRANSFORMATION_LOG);
	public static final Supplier<OrnamentTFPole> mining_log_pole = HELPER.pole(TFOrnamentBuilders.MINING_LOG);
	public static final Supplier<OrnamentTFPole> sorting_log_pole = HELPER.pole(TFOrnamentBuilders.SORTING_LOG);
	public static final Supplier<OrnamentTFPole> twilight_oak_plank_pole = HELPER.pole(TFOrnamentBuilders.TWILIGHT_OAK_PLANKS);
	public static final Supplier<OrnamentTFPole> canopy_plank_pole = HELPER.pole(TFOrnamentBuilders.CANOPY_PLANKS);
	public static final Supplier<OrnamentTFPole> mangrove_plank_pole = HELPER.pole(TFOrnamentBuilders.MANGROVE_PLANKS);
	public static final Supplier<OrnamentTFPole> dark_oak_plank_pole = HELPER.pole(TFOrnamentBuilders.DARK_OAK_PLANKS);
	public static final Supplier<OrnamentTFPole> time_plank_pole = HELPER.pole(TFOrnamentBuilders.TIME_PLANKS);
	public static final Supplier<OrnamentTFPole> transformation_plank_pole = HELPER.pole(TFOrnamentBuilders.TRANSFORMATION_PLANKS);
	public static final Supplier<OrnamentTFPole> mining_plank_pole = HELPER.pole(TFOrnamentBuilders.MINING_PLANKS);
	public static final Supplier<OrnamentTFPole> sorting_plank_pole = HELPER.pole(TFOrnamentBuilders.SORTING_PLANKS);

	public static final Supplier<OrnamentTFBeam> ironwood_beam = HELPER.beam(TFOrnamentBuilders.IRONWOOD);
	public static final Supplier<OrnamentTFBeam> fiery_beam = HELPER.beam(TFOrnamentBuilders.FIERY);
	public static final Supplier<OrnamentTFBeam> steeleaf_beam = HELPER.beam(TFOrnamentBuilders.STEELEAF);
	public static final Supplier<OrnamentTFBeam> arctic_fur_beam = HELPER.beam(TFOrnamentBuilders.ARCTIC_FUR);
	public static final Supplier<OrnamentTFBeam> carminite_beam = HELPER.beam(TFOrnamentBuilders.CARMINITE);
	public static final Supplier<OrnamentTFBeam> twilight_oak_log_beam = HELPER.beam(TFOrnamentBuilders.TWILIGHT_OAK_LOG);
	public static final Supplier<OrnamentTFBeam> canopy_log_beam = HELPER.beam(TFOrnamentBuilders.CANOPY_LOG);
	public static final Supplier<OrnamentTFBeam> mangrove_log_beam = HELPER.beam(TFOrnamentBuilders.MANGROVE_LOG);
	public static final Supplier<OrnamentTFBeam> dark_oak_log_beam = HELPER.beam(TFOrnamentBuilders.DARK_OAK_LOG);
	public static final Supplier<OrnamentTFBeam> time_log_beam = HELPER.beam(TFOrnamentBuilders.TIME_LOG);
	public static final Supplier<OrnamentTFBeam> transformation_log_beam = HELPER.beam(TFOrnamentBuilders.TRANSFORMATION_LOG);
	public static final Supplier<OrnamentTFBeam> mining_log_beam = HELPER.beam(TFOrnamentBuilders.MINING_LOG);
	public static final Supplier<OrnamentTFBeam> sorting_log_beam = HELPER.beam(TFOrnamentBuilders.SORTING_LOG);
	public static final Supplier<OrnamentTFBeam> twilight_oak_plank_beam = HELPER.beam(TFOrnamentBuilders.TWILIGHT_OAK_PLANKS);
	public static final Supplier<OrnamentTFBeam> canopy_plank_beam = HELPER.beam(TFOrnamentBuilders.CANOPY_PLANKS);
	public static final Supplier<OrnamentTFBeam> mangrove_plank_beam = HELPER.beam(TFOrnamentBuilders.MANGROVE_PLANKS);
	public static final Supplier<OrnamentTFBeam> dark_oak_plank_beam = HELPER.beam(TFOrnamentBuilders.DARK_OAK_PLANKS);
	public static final Supplier<OrnamentTFBeam> time_plank_beam = HELPER.beam(TFOrnamentBuilders.TIME_PLANKS);
	public static final Supplier<OrnamentTFBeam> transformation_plank_beam = HELPER.beam(TFOrnamentBuilders.TRANSFORMATION_PLANKS);
	public static final Supplier<OrnamentTFBeam> mining_plank_beam = HELPER.beam(TFOrnamentBuilders.MINING_PLANKS);
	public static final Supplier<OrnamentTFBeam> sorting_plank_beam = HELPER.beam(TFOrnamentBuilders.SORTING_PLANKS);

	public static final Supplier<OrnamentTFWall> ironwood_wall = HELPER.wall(TFOrnamentBuilders.IRONWOOD);
	public static final Supplier<OrnamentTFWall> fiery_wall = HELPER.wall(TFOrnamentBuilders.FIERY);
	public static final Supplier<OrnamentTFWall> steeleaf_wall = HELPER.wall(TFOrnamentBuilders.STEELEAF);
	public static final Supplier<OrnamentTFWall> arctic_fur_wall = HELPER.wall(TFOrnamentBuilders.ARCTIC_FUR);
	public static final Supplier<OrnamentTFWall> carminite_wall = HELPER.wall(TFOrnamentBuilders.CARMINITE);
	public static final Supplier<OrnamentTFWall> twilight_oak_log_wall = HELPER.wall(TFOrnamentBuilders.TWILIGHT_OAK_LOG);
	public static final Supplier<OrnamentTFWall> canopy_log_wall = HELPER.wall(TFOrnamentBuilders.CANOPY_LOG);
	public static final Supplier<OrnamentTFWall> mangrove_log_wall = HELPER.wall(TFOrnamentBuilders.MANGROVE_LOG);
	public static final Supplier<OrnamentTFWall> dark_oak_log_wall = HELPER.wall(TFOrnamentBuilders.DARK_OAK_LOG);
	public static final Supplier<OrnamentTFWall> time_log_wall = HELPER.wall(TFOrnamentBuilders.TIME_LOG);
	public static final Supplier<OrnamentTFWall> transformation_log_wall = HELPER.wall(TFOrnamentBuilders.TRANSFORMATION_LOG);
	public static final Supplier<OrnamentTFWall> mining_log_wall = HELPER.wall(TFOrnamentBuilders.MINING_LOG);
	public static final Supplier<OrnamentTFWall> sorting_log_wall = HELPER.wall(TFOrnamentBuilders.SORTING_LOG);
	public static final Supplier<OrnamentTFWall> twilight_oak_plank_wall = HELPER.wall(TFOrnamentBuilders.TWILIGHT_OAK_PLANKS);
	public static final Supplier<OrnamentTFWall> canopy_plank_wall = HELPER.wall(TFOrnamentBuilders.CANOPY_PLANKS);
	public static final Supplier<OrnamentTFWall> mangrove_plank_wall = HELPER.wall(TFOrnamentBuilders.MANGROVE_PLANKS);
	public static final Supplier<OrnamentTFWall> dark_oak_plank_wall = HELPER.wall(TFOrnamentBuilders.DARK_OAK_PLANKS);
	public static final Supplier<OrnamentTFWall> time_plank_wall = HELPER.wall(TFOrnamentBuilders.TIME_PLANKS);
	public static final Supplier<OrnamentTFWall> transformation_plank_wall = HELPER.wall(TFOrnamentBuilders.TRANSFORMATION_PLANKS);
	public static final Supplier<OrnamentTFWall> mining_plank_wall = HELPER.wall(TFOrnamentBuilders.MINING_PLANKS);
	public static final Supplier<OrnamentTFWall> sorting_plank_wall = HELPER.wall(TFOrnamentBuilders.SORTING_PLANKS);

	public static final Supplier<OrnamentTFSaddleDoor> ironwood_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.IRONWOOD);
	public static final Supplier<OrnamentTFSaddleDoor> fiery_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.FIERY);
	public static final Supplier<OrnamentTFSaddleDoor> steeleaf_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.STEELEAF);
	public static final Supplier<OrnamentTFSaddleDoor> arctic_fur_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.ARCTIC_FUR);
	public static final Supplier<OrnamentTFSaddleDoor> carminite_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.CARMINITE);
	public static final Supplier<OrnamentTFSaddleDoor> twilight_oak_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TWILIGHT_OAK_LOG);
	public static final Supplier<OrnamentTFSaddleDoor> canopy_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.CANOPY_LOG);
	public static final Supplier<OrnamentTFSaddleDoor> mangrove_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MANGROVE_LOG);
	public static final Supplier<OrnamentTFSaddleDoor> dark_oak_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.DARK_OAK_LOG);
	public static final Supplier<OrnamentTFSaddleDoor> time_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TIME_LOG);
	public static final Supplier<OrnamentTFSaddleDoor> transformation_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TRANSFORMATION_LOG);
	public static final Supplier<OrnamentTFSaddleDoor> mining_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MINING_LOG);
	public static final Supplier<OrnamentTFSaddleDoor> sorting_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.SORTING_LOG);
	public static final Supplier<OrnamentTFSaddleDoor> twilight_oak_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TWILIGHT_OAK_PLANKS);
	public static final Supplier<OrnamentTFSaddleDoor> canopy_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.CANOPY_PLANKS);
	public static final Supplier<OrnamentTFSaddleDoor> mangrove_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MANGROVE_PLANKS);
	public static final Supplier<OrnamentTFSaddleDoor> dark_oak_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.DARK_OAK_PLANKS);
	public static final Supplier<OrnamentTFSaddleDoor> time_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TIME_PLANKS);
	public static final Supplier<OrnamentTFSaddleDoor> transformation_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TRANSFORMATION_PLANKS);
	public static final Supplier<OrnamentTFSaddleDoor> mining_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MINING_PLANKS);
	public static final Supplier<OrnamentTFSaddleDoor> sorting_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.SORTING_PLANKS);

	public static final RegistryObject<OrnamentTFSaddleDoor> ironwood_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.IRONWOOD);
	public static final RegistryObject<OrnamentTFSaddleDoor> fiery_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.FIERY);
	public static final RegistryObject<OrnamentTFSaddleDoor> steeleaf_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.STEELEAF);
	public static final RegistryObject<OrnamentTFSaddleDoor> arctic_fur_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.ARCTIC_FUR);
	public static final RegistryObject<OrnamentTFSaddleDoor> carminite_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.CARMINITE);
	public static final RegistryObject<OrnamentTFSaddleDoor> twilight_oak_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TWILIGHT_OAK_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> canopy_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.CANOPY_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> mangrove_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MANGROVE_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> dark_oak_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.DARK_OAK_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> time_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TIME_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> transformation_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TRANSFORMATION_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> mining_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MINING_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> sorting_log_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.SORTING_LOG);
	public static final RegistryObject<OrnamentTFSaddleDoor> twilight_oak_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TWILIGHT_OAK_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> canopy_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.CANOPY_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> mangrove_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MANGROVE_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> dark_oak_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.DARK_OAK_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> time_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TIME_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> transformation_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.TRANSFORMATION_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> mining_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.MINING_PLANKS);
	public static final RegistryObject<OrnamentTFSaddleDoor> sorting_plank_saddle_door = HELPER.saddledoor(TFOrnamentBuilders.SORTING_PLANKS);
}
